### ISSUE TITLE
Command-line interface meta-ticket

### ISSUE THREAD

**Issue by ato** [nla/doss#5]
List of commands the DOSS admin CLI should support. Feel free to create tickets for these individual tasks and work on them. Also if you think something would be a good idea add it to the ideas section and then ask Alex or Bryan if they think it fits into the DOSS plan.

You can use the CLI like this:

```
mvn compile
bin/doss.sh help
```
#### General
- [x] version - display version information #43
- [x] init - intialize the blob store #50
#### Blobs
- [x] cat <blob1> [<blob2> ...] - prints blobs to standard output #3
- [x] get <blob1> [<blob2> ...] - copy blobs to current working directory
- [x] stat <blob1> [<blob2> ...] - display metadata about a blob (eg it's size, which container it's in) #38
- [x] put <file1> [<file2>...] - stores files as blobs #10 
#### Transactions
- [ ] tx - print summary of open and prepared transactinos
- [ ] commit <tx-id> - manually commit a transaction
- [ ] rollback <tx-id> - manually rollback a transaction
#### Containers

Commands for displaying information about containers.
#### Integrity checking

Commands for controlling integrity checking, viewing reports of any corrupt files etc.
#### Authentication

Commands to grant or deny systems access to DOSS. (Certificates or password or whatever, I dunno yet).
#### Ideas

Add ideas here, get Alex or Bryan to approve them before starting to implement them though.
